name       : python-enzyme
version    : 0.4.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/e/enzyme/enzyme-0.4.1.tar.gz : f2167fa97c24d1103a94d4bf4eb20f00ca76c38a37499821049253b2059c62bb
license    : Apache-2.0
component  : programming.python
summary    : Python video metadata parser
description: |
    Enzyme is a Python module to parse video metadata.
build      : |
    %python3_setup
install    : |
    %python3_install
