name       : python-enzyme
version    : 0.4.1
release    : 1
source     :
    - https://pypi.python.org/packages/dd/99/e4eee822d9390ebf1f63a7a67e8351c09fb7cd75262e5bb1a5256898def9/enzyme-0.4.1.tar.gz : f2167fa97c24d1103a94d4bf4eb20f00ca76c38a37499821049253b2059c62bb
license    : Apache-2.0
component  : programming.python
summary    : Python video metadata parser
description: |
    Python video metadata parser
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
